### ISSUE TITLE
Cannot find module on Windows platform

### ISSUE THREAD

**Issue by jdnichollsc** [samuelnovaes/phaser-runtime#2]
Hi man,

This npm package doesn't work on Windows. For example
```
D:\Phaser\Electron>phaser Kinetic
Cannot find module D:\Phaser\Electron/Kinetic/index.js
```

Regards, Nicholls

**Comment by samuelnovaes** [comment]
Thanks @jdnichollsc !
Issue solved.
![virtualbox_windows 7_17_02_2017_07_43_01](https://cloud.githubusercontent.com/assets/16156987/23060522/30b85702-f4e5-11e6-8cca-bf2c651ea7d6.png)
